In [4]:

!pip install numpy
!pip install pandas
!pip install tensorflow_cpu
!pip install --upgrade ml_dtypes jax jaxlib

Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: tensorflow_cpu in /usr/local/lib/python3.12/dist-packages (2.18.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (18.1.1)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (26.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (1.80.0)
Requirement already satisfied: tensorboard<2.19,>=2.18 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (2.18.0)
Requirement already satisfied: keras>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (3.13.2)
Requirement already satisfied: numpy<2.1.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (3.16.0)
Requirement already satisfied: ml-dtypes<0.5.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow_cpu) (0.4.1)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow_cpu) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow_cpu) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow_cpu) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.5.0->tensorflow_cpu) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow_cpu) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow_cpu) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow_cpu) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow_cpu) (2026.4.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard<2.19,>=2.18->tensorflow_cpu) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard<2.19,>=2.18->tensorflow_cpu) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard<2.19,>=2.18->tensorflow_cpu) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard<2.19,>=2.18->tensorflow_cpu) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow_cpu) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.5.0->tensorflow_cpu) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.5.0->tensorflow_cpu) (0.1.2)

In [5]:
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [1]:
import pandas as pd
import numpy as np
import keras

import warnings
warnings.simplefilter('ignore', FutureWarning)

In [2]:
filepath='https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DL0101EN/labs/data/concrete_data.csv'
concrete_data = pd.read_csv(filepath)

concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [3]:
concrete_data.shape

(1030, 9)

In [5]:
concrete_data.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [6]:
concrete_data.isnull().sum()

Cement                0
Blast Furnace Slag    0
Fly Ash               0
Water                 0
Superplasticizer      0
Coarse Aggregate      0
Fine Aggregate        0
Age                   0
Strength              0
dtype: int64

In [7]:
predictors = concrete_data[concrete_data.columns[concrete_data.columns != 'Strength']] # all columns except Strength
target = concrete_data['Strength'] # Strength column

In [8]:
predictors.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360

In [9]:
target.head()

0    79.99
1    61.89
2    40.27
3    41.05
4    44.30
Name: Strength, dtype: float64

In [10]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [15]:
n_cols = predictors_norm.shape[1] # number of predictors

In [16]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Input

In [17]:
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))

    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

##Train and Test the Network

In [18]:
# build the model
model = regression_model()

In [19]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 1s - 53ms/step - loss: 1651.8341 - val_loss: 1139.2144
Epoch 2/100
23/23 - 0s - 4ms/step - loss: 1518.8060 - val_loss: 999.3875
Epoch 3/100
23/23 - 0s - 4ms/step - loss: 1291.3169 - val_loss: 780.8454
Epoch 4/100
23/23 - 0s - 4ms/step - loss: 944.1327 - val_loss: 506.3899
Epoch 5/100
23/23 - 0s - 4ms/step - loss: 557.3205 - val_loss: 286.8175
Epoch 6/100
23/23 - 0s - 4ms/step - loss: 312.2859 - val_loss: 193.6299
Epoch 7/100
23/23 - 0s - 5ms/step - loss: 238.4297 - val_loss: 172.6438
Epoch 8/100
23/23 - 0s - 4ms/step - loss: 219.3628 - val_loss: 164.2384
Epoch 9/100
23/23 - 0s - 6ms/step - loss: 206.1648 - val_loss: 162.6405
Epoch 10/100
23/23 - 0s - 7ms/step - loss: 196.9653 - val_loss: 158.0462
Epoch 11/100
23/23 - 0s - 6ms/step - loss: 189.9171 - val_loss: 158.3265
Epoch 12/100
23/23 - 0s - 7ms/step - loss: 183.7579 - val_loss: 156.8708
Epoch 13/100
23/23 - 0s - 5ms/step - loss: 178.2216 - val_loss: 154.1257
Epoch 14/100
23/23 - 0s - 5ms/step - loss: 173.8536 - val_loss: 155.2263
Epoch 15/100
23/23 - 0s - 6ms/step - loss: 169.5586 - val_loss: 153.1862
Epoch 16/100
23/23 - 0s - 5ms/step - loss: 166.3797 - val_loss: 153.5788
Epoch 17/100
23/23 - 0s - 8ms/step - loss: 163.0435 - val_loss: 151.6803
Epoch 18/100
23/23 - 0s - 7ms/step - loss: 159.7395 - val_loss: 153.7567
Epoch 19/100
23/23 - 0s - 11ms/step - loss: 157.2483 - val_loss: 153.6060
Epoch 20/100
23/23 - 0s - 4ms/step - loss: 154.3228 - val_loss: 152.9691
Epoch 21/100
23/23 - 0s - 4ms/step - loss: 151.9759 - val_loss: 153.7818
Epoch 22/100
23/23 - 0s - 4ms/step - loss: 150.0428 - val_loss: 154.1784
Epoch 23/100
23/23 - 0s - 4ms/step - loss: 148.0988 - val_loss: 150.9907
Epoch 24/100
23/23 - 0s - 4ms/step - loss: 146.5950 - val_loss: 155.2258
Epoch 25/100
23/23 - 0s - 4ms/step - loss: 144.2221 - val_loss: 154.3030
Epoch 26/100
23/23 - 0s - 4ms/step - loss: 142.7388 - val_loss: 154.8486
Epoch 27/100
23/23 - 0s - 4ms/step - loss: 141.6142 - val_loss: 156.8723
Epoch 28/100
23/23 - 0s - 4ms/step - loss: 140.1205 - val_loss: 153.7141
Epoch 29/100
23/23 - 0s - 4ms/step - loss: 138.6673 - val_loss: 155.5595
Epoch 30/100
23/23 - 0s - 4ms/step - loss: 138.4069 - val_loss: 157.4327
Epoch 31/100
23/23 - 0s - 4ms/step - loss: 136.6384 - val_loss: 155.3881
Epoch 32/100
23/23 - 0s - 5ms/step - loss: 134.9783 - val_loss: 152.2177
Epoch 33/100
23/23 - 0s - 4ms/step - loss: 134.5508 - val_loss: 155.9341
Epoch 34/100
23/23 - 0s - 4ms/step - loss: 132.3095 - val_loss: 157.7652
Epoch 35/100
23/23 - 0s - 4ms/step - loss: 131.8603 - val_loss: 156.6083
Epoch 36/100
23/23 - 0s - 4ms/step - loss: 130.0907 - val_loss: 156.2465
Epoch 37/100
23/23 - 0s - 4ms/step - loss: 129.2688 - val_loss: 155.8180
Epoch 38/100
23/23 - 0s - 4ms/step - loss: 128.3929 - val_loss: 155.8791
Epoch 39/100
23/23 - 0s - 4ms/step - loss: 126.7998 - val_loss: 158.6654
Epoch 40/100
23/23 - 0s - 5ms/step - loss: 127.4571 - val_loss: 155.3699
Epoch 41/100
23/23 - 0s - 4ms/step - loss: 125.4073 - val_loss: 154.1348
Epoch 42/100
23/23 - 0s - 5ms/step - loss: 124.1968 - val_loss: 157.0987
Epoch 43/100
23/23 - 0s - 4ms/step - loss: 123.4662 - val_loss: 156.8329
Epoch 44/100
23/23 - 0s - 5ms/step - loss: 122.0321 - val_loss: 155.4301
Epoch 45/100
23/23 - 0s - 4ms/step - loss: 121.0991 - val_loss: 156.1265
Epoch 46/100
23/23 - 0s - 4ms/step - loss: 120.0540 - val_loss: 154.3836
Epoch 47/100
23/23 - 0s - 4ms/step - loss: 119.1145 - val_loss: 156.9095
Epoch 48/100
23/23 - 0s - 4ms/step - loss: 117.9266 - val_loss: 155.3731
Epoch 49/100
23/23 - 0s - 4ms/step - loss: 116.8272 - val_loss: 150.0706
Epoch 50/100
23/23 - 0s - 4ms/step - loss: 115.4454 - val_loss: 151.8161
Epoch 51/100
23/23 - 0s - 4ms/step - loss: 114.3882 - val_loss: 151.6097
Epoch 52/100
23/23 - 0s - 4ms/step - loss: 113.8718 - val_loss: 149.3515
Epoch 53/100
23/23 - 0s - 4ms/step - loss: 112.9836 - val_loss: 153.0415
Epoch 54/100
23/23 - 0s - 4ms/step - loss: 111.5428 - val_loss: 148.9206
Epoch 55/100
23/23 - 0s - 4ms/step - loss: 110.5488 - val_loss: 147.3839
Epoch 56/100
23/23 - 0s - 4ms/step - loss: 108.8131 - val_loss: 148.3870
Epoch 57/100
23/23 - 0s - 4ms/step - loss: 107.6780 - val_loss: 141.3861
Epoch 58/100
23/23 - 0s - 4ms/step - loss: 106.8174 - val_loss: 148.9550
Epoch 59/100
23/23 - 0s - 4ms/step - loss: 105.9835 - val_loss: 143.5052
Epoch 60/100
23/23 - 0s - 4ms/step - loss: 103.9948 - val_loss: 144.9374
Epoch 61/100
23/23 - 0s - 4ms/step - loss: 102.7412 - val_loss: 146.1800
Epoch 62/100
23/23 - 0s - 5ms/step - loss: 101.4359 - val_loss: 145.9298
Epoch 63/100
23/23 - 0s - 4ms/step - loss: 101.1106 - val_loss: 142.4711
Epoch 64/100
23/23 - 0s - 4ms/step - loss: 98.2276 - val_loss: 139.9592
Epoch 65/100
23/23 - 0s - 4ms/step - loss: 96.4732 - val_loss: 138.6335
Epoch 66/100
23/23 - 0s - 4ms/step - loss: 95.1687 - val_loss: 146.5457
Epoch 67/100
23/23 - 0s - 4ms/step - loss: 94.3130 - val_loss: 141.8892
Epoch 68/100
23/23 - 0s - 4ms/step - loss: 91.5977 - val_loss: 140.2139
Epoch 69/100
23/23 - 0s - 4ms/step - loss: 89.6640 - val_loss: 140.9820
Epoch 70/100
23/23 - 0s - 6ms/step - loss: 87.8536 - val_loss: 129.6652
Epoch 71/100
23/23 - 0s - 4ms/step - loss: 86.0446 - val_loss: 134.0219
Epoch 72/100
23/23 - 0s - 4ms/step - loss: 81.8203 - val_loss: 136.2528
Epoch 73/100
23/23 - 0s - 5ms/step - loss: 78.9688 - val_loss: 134.4037
Epoch 74/100
23/23 - 0s - 4ms/step - loss: 76.1844 - val_loss: 133.6764
Epoch 75/100
23/23 - 0s - 5ms/step - loss: 73.5269 - val_loss: 132.1160
Epoch 76/100
23/23 - 0s - 5ms/step - loss: 69.5604 - val_loss: 132.1959
Epoch 77/100
23/23 - 0s - 4ms/step - loss: 65.4767 - val_loss: 132.8763
Epoch 78/100
23/23 - 0s - 4ms/step - loss: 62.6502 - val_loss: 129.3807
Epoch 79/100
23/23 - 0s - 4ms/step - loss: 59.5945 - val_loss: 127.3448
Epoch 80/100
23/23 - 0s - 4ms/step - loss: 57.7154 - val_loss: 124.9250
Epoch 81/100
23/23 - 0s - 4ms/step - loss: 55.5168 - val_loss: 132.7243
Epoch 82/100
23/23 - 0s - 4ms/step - loss: 54.3006 - val_loss: 121.1252
Epoch 83/100
23/23 - 0s - 5ms/step - loss: 52.1863 - val_loss: 129.7988
Epoch 84/100
23/23 - 0s - 4ms/step - loss: 50.9708 - val_loss: 121.5554
Epoch 85/100
23/23 - 0s - 5ms/step - loss: 49.2875 - val_loss: 135.9851
Epoch 86/100
23/23 - 0s - 5ms/step - loss: 49.5606 - val_loss: 122.1187
Epoch 87/100
23/23 - 0s - 4ms/step - loss: 47.1634 - val_loss: 121.1837
Epoch 88/100
23/23 - 0s - 4ms/step - loss: 45.7451 - val_loss: 125.3270
Epoch 89/100
23/23 - 0s - 5ms/step - loss: 44.7218 - val_loss: 124.9836
Epoch 90/100
23/23 - 0s - 4ms/step - loss: 44.3771 - val_loss: 131.2745
Epoch 91/100
23/23 - 0s - 4ms/step - loss: 43.6306 - val_loss: 123.7868
Epoch 92/100
23/23 - 0s - 4ms/step - loss: 42.5069 - val_loss: 130.2652
Epoch 93/100
23/23 - 0s - 6ms/step - loss: 41.7391 - val_loss: 124.1075
Epoch 94/100
23/23 - 0s - 4ms/step - loss: 41.6756 - val_loss: 126.8895
Epoch 95/100
23/23 - 0s - 4ms/step - loss: 41.3927 - val_loss: 136.8278
Epoch 96/100
23/23 - 0s - 4ms/step - loss: 40.0672 - val_loss: 129.1123
Epoch 97/100
23/23 - 0s - 4ms/step - loss: 39.4980 - val_loss: 131.5882
Epoch 98/100
23/23 - 0s - 4ms/step - loss: 38.5514 - val_loss: 132.5175
Epoch 99/100
23/23 - 0s - 4ms/step - loss: 38.8875 - val_loss: 142.7823
Epoch 100/100
23/23 - 0s - 4ms/step - loss: 37.7966 - val_loss: 121.5156

Now using the same dateset,try to recreate regression model featuring five hidden layers, each with 50 nodes and ReLU activation functions, a single output layer, optimized using the Adam optimizer.

In [20]:
# define regression model
def regression_model1():
    # create model
    model = Sequential()
    model.add(Input(shape=(n_cols,)))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(1))

    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [21]:
# build the model
model = regression_model1()

# fit the model
model.fit(predictors_norm, target, validation_split=0.3, epochs=100, verbose=2)

Epoch 1/100
23/23 - 2s - 97ms/step - loss: 1646.3145 - val_loss: 1089.6525
Epoch 2/100
23/23 - 0s - 4ms/step - loss: 1083.7666 - val_loss: 268.8377
Epoch 3/100
23/23 - 0s - 5ms/step - loss: 358.4762 - val_loss: 234.8820
Epoch 4/100
23/23 - 0s - 5ms/step - loss: 248.1700 - val_loss: 192.3551
Epoch 5/100
23/23 - 0s - 5ms/step - loss: 219.2468 - val_loss: 178.2192
Epoch 6/100
23/23 - 0s - 4ms/step - loss: 197.4116 - val_loss: 176.5494
Epoch 7/100
23/23 - 0s - 5ms/step - loss: 180.9093 - val_loss: 177.7074
Epoch 8/100
23/23 - 0s - 5ms/step - loss: 167.0780 - val_loss: 173.0230
Epoch 9/100
23/23 - 0s - 5ms/step - loss: 153.7835 - val_loss: 182.9456
Epoch 10/100
23/23 - 0s - 5ms/step - loss: 140.3958 - val_loss: 168.8097
Epoch 11/100
23/23 - 0s - 4ms/step - loss: 124.1319 - val_loss: 173.5090
Epoch 12/100
23/23 - 0s - 5ms/step - loss: 111.1249 - val_loss: 191.3556
Epoch 13/100
23/23 - 0s - 6ms/step - loss: 99.6766 - val_loss: 167.8536
Epoch 14/100
23/23 - 0s - 4ms/step - loss: 89.6389 - val_loss: 170.8929
Epoch 15/100
23/23 - 0s - 4ms/step - loss: 89.2415 - val_loss: 174.5437
Epoch 16/100
23/23 - 0s - 4ms/step - loss: 72.7072 - val_loss: 158.7970
Epoch 17/100
23/23 - 0s - 4ms/step - loss: 65.4953 - val_loss: 173.5960
Epoch 18/100
23/23 - 0s - 5ms/step - loss: 59.9710 - val_loss: 181.8917
Epoch 19/100
23/23 - 0s - 5ms/step - loss: 55.8462 - val_loss: 149.0089
Epoch 20/100
23/23 - 0s - 5ms/step - loss: 50.5885 - val_loss: 148.0414
Epoch 21/100
23/23 - 0s - 5ms/step - loss: 47.1247 - val_loss: 159.3681
Epoch 22/100
23/23 - 0s - 5ms/step - loss: 45.6337 - val_loss: 146.4048
Epoch 23/100
23/23 - 0s - 5ms/step - loss: 43.2138 - val_loss: 156.5806
Epoch 24/100
23/23 - 0s - 4ms/step - loss: 42.4066 - val_loss: 152.3402
Epoch 25/100
23/23 - 0s - 5ms/step - loss: 38.5811 - val_loss: 132.3287
Epoch 26/100
23/23 - 0s - 4ms/step - loss: 37.7139 - val_loss: 151.7660
Epoch 27/100
23/23 - 0s - 4ms/step - loss: 37.2625 - val_loss: 124.8090
Epoch 28/100
23/23 - 0s - 4ms/step - loss: 34.2790 - val_loss: 119.9542
Epoch 29/100
23/23 - 0s - 4ms/step - loss: 32.3963 - val_loss: 111.4532
Epoch 30/100
23/23 - 0s - 5ms/step - loss: 32.8261 - val_loss: 132.8206
Epoch 31/100
23/23 - 0s - 4ms/step - loss: 31.2472 - val_loss: 122.6709
Epoch 32/100
23/23 - 0s - 5ms/step - loss: 30.8393 - val_loss: 132.9260
Epoch 33/100
23/23 - 0s - 5ms/step - loss: 28.6705 - val_loss: 133.4166
Epoch 34/100
23/23 - 0s - 5ms/step - loss: 30.8227 - val_loss: 118.7274
Epoch 35/100
23/23 - 0s - 5ms/step - loss: 31.8899 - val_loss: 111.4307
Epoch 36/100
23/23 - 0s - 5ms/step - loss: 29.3864 - val_loss: 109.9267
Epoch 37/100
23/23 - 0s - 5ms/step - loss: 26.2910 - val_loss: 99.2157
Epoch 38/100
23/23 - 0s - 5ms/step - loss: 24.8468 - val_loss: 120.2023
Epoch 39/100
23/23 - 0s - 5ms/step - loss: 24.5480 - val_loss: 99.6608
Epoch 40/100
23/23 - 0s - 5ms/step - loss: 24.6529 - val_loss: 120.4239
Epoch 41/100
23/23 - 0s - 4ms/step - loss: 24.2131 - val_loss: 102.9679
Epoch 42/100
23/23 - 0s - 4ms/step - loss: 22.9083 - val_loss: 99.5680
Epoch 43/100
23/23 - 0s - 4ms/step - loss: 23.0471 - val_loss: 108.6265
Epoch 44/100
23/23 - 0s - 4ms/step - loss: 22.2598 - val_loss: 117.2079
Epoch 45/100
23/23 - 0s - 4ms/step - loss: 21.8626 - val_loss: 103.1384
Epoch 46/100
23/23 - 0s - 4ms/step - loss: 20.1481 - val_loss: 85.9002
Epoch 47/100
23/23 - 0s - 4ms/step - loss: 21.1812 - val_loss: 100.4490
Epoch 48/100
23/23 - 0s - 4ms/step - loss: 19.8879 - val_loss: 97.8488
Epoch 49/100
23/23 - 0s - 4ms/step - loss: 20.5451 - val_loss: 86.6190
Epoch 50/100
23/23 - 0s - 4ms/step - loss: 19.2183 - val_loss: 93.8592
Epoch 51/100
23/23 - 0s - 4ms/step - loss: 18.8640 - val_loss: 97.0599
Epoch 52/100
23/23 - 0s - 4ms/step - loss: 19.6368 - val_loss: 93.9068
Epoch 53/100
23/23 - 0s - 4ms/step - loss: 18.5664 - val_loss: 92.5051
Epoch 54/100
23/23 - 0s - 4ms/step - loss: 18.9926 - val_loss: 87.8948
Epoch 55/100
23/23 - 0s - 4ms/step - loss: 17.8910 - val_loss: 94.2862
Epoch 56/100
23/23 - 0s - 4ms/step - loss: 17.9294 - val_loss: 96.2181
Epoch 57/100
23/23 - 0s - 4ms/step - loss: 17.0369 - val_loss: 92.8608
Epoch 58/100
23/23 - 0s - 4ms/step - loss: 18.4632 - val_loss: 88.6686
Epoch 59/100
23/23 - 0s - 4ms/step - loss: 17.0709 - val_loss: 87.7536
Epoch 60/100
23/23 - 0s - 4ms/step - loss: 18.2122 - val_loss: 97.7636
Epoch 61/100
23/23 - 0s - 4ms/step - loss: 16.9882 - val_loss: 87.7662
Epoch 62/100
23/23 - 0s - 5ms/step - loss: 17.6708 - val_loss: 89.4943
Epoch 63/100
23/23 - 0s - 6ms/step - loss: 17.1103 - val_loss: 99.2821
Epoch 64/100
23/23 - 0s - 4ms/step - loss: 16.4867 - val_loss: 88.6849
Epoch 65/100
23/23 - 0s - 4ms/step - loss: 16.4414 - val_loss: 98.0548
Epoch 66/100
23/23 - 0s - 5ms/step - loss: 17.4374 - val_loss: 92.3118
Epoch 67/100
23/23 - 0s - 4ms/step - loss: 16.6674 - val_loss: 91.1338
Epoch 68/100
23/23 - 0s - 4ms/step - loss: 15.3776 - val_loss: 99.2648
Epoch 69/100
23/23 - 0s - 5ms/step - loss: 16.4204 - val_loss: 88.5544
Epoch 70/100
23/23 - 0s - 5ms/step - loss: 14.4935 - val_loss: 91.4405
Epoch 71/100
23/23 - 0s - 5ms/step - loss: 14.5080 - val_loss: 95.8164
Epoch 72/100
23/23 - 0s - 5ms/step - loss: 16.1241 - val_loss: 93.7012
Epoch 73/100
23/23 - 0s - 5ms/step - loss: 15.7063 - val_loss: 88.5335
Epoch 74/100
23/23 - 0s - 5ms/step - loss: 14.1721 - val_loss: 92.8834
Epoch 75/100
23/23 - 0s - 5ms/step - loss: 15.3640 - val_loss: 90.8666
Epoch 76/100
23/23 - 0s - 4ms/step - loss: 14.7290 - val_loss: 96.7080
Epoch 77/100
23/23 - 0s - 5ms/step - loss: 15.2388 - val_loss: 95.5809
Epoch 78/100
23/23 - 0s - 5ms/step - loss: 14.4450 - val_loss: 93.7117
Epoch 79/100
23/23 - 0s - 5ms/step - loss: 15.4364 - val_loss: 99.0508
Epoch 80/100
23/23 - 0s - 4ms/step - loss: 14.8413 - val_loss: 97.8442
Epoch 81/100
23/23 - 0s - 5ms/step - loss: 16.7563 - val_loss: 88.0629
Epoch 82/100
23/23 - 0s - 4ms/step - loss: 15.7072 - val_loss: 86.7106
Epoch 83/100
23/23 - 0s - 4ms/step - loss: 14.0174 - val_loss: 87.0564
Epoch 84/100
23/23 - 0s - 4ms/step - loss: 14.9418 - val_loss: 100.7963
Epoch 85/100
23/23 - 0s - 4ms/step - loss: 13.3040 - val_loss: 89.7410
Epoch 86/100
23/23 - 0s - 4ms/step - loss: 13.4072 - val_loss: 93.0120
Epoch 87/100
23/23 - 0s - 4ms/step - loss: 13.9618 - val_loss: 89.2002
Epoch 88/100
23/23 - 0s - 5ms/step - loss: 13.0418 - val_loss: 89.6554
Epoch 89/100
23/23 - 0s - 4ms/step - loss: 13.8663 - val_loss: 95.9856
Epoch 90/100
23/23 - 0s - 4ms/step - loss: 14.5946 - val_loss: 95.8189
Epoch 91/100
23/23 - 0s - 5ms/step - loss: 13.8298 - val_loss: 83.9497
Epoch 92/100
23/23 - 0s - 5ms/step - loss: 13.4347 - val_loss: 91.0616
Epoch 93/100
23/23 - 0s - 9ms/step - loss: 12.2502 - val_loss: 99.6814
Epoch 94/100
23/23 - 0s - 12ms/step - loss: 13.2198 - val_loss: 100.3874
Epoch 95/100
23/23 - 0s - 8ms/step - loss: 13.2815 - val_loss: 89.1940
Epoch 96/100
23/23 - 0s - 6ms/step - loss: 12.4458 - val_loss: 95.7380
Epoch 97/100
23/23 - 0s - 13ms/step - loss: 12.3726 - val_loss: 95.1752
Epoch 98/100
23/23 - 0s - 7ms/step - loss: 12.6234 - val_loss: 92.2696
Epoch 99/100
23/23 - 0s - 7ms/step - loss: 11.3506 - val_loss: 91.3565
Epoch 100/100
23/23 - 0s - 4ms/step - loss: 12.4879 - val_loss: 89.4099

Train and evaluate the model simultaneously using the fit() method by reserving 10% of the data for validation and training the model for 100 epochs

In [22]:
# fit the model
model.fit(predictors_norm, target, validation_split=0.1, epochs=100, verbose=2)

Epoch 1/100
29/29 - 0s - 4ms/step - loss: 24.8942 - val_loss: 59.2498
Epoch 2/100
29/29 - 0s - 4ms/step - loss: 22.6669 - val_loss: 55.8618
Epoch 3/100
29/29 - 0s - 3ms/step - loss: 19.9562 - val_loss: 40.1154
Epoch 4/100
29/29 - 0s - 3ms/step - loss: 20.9817 - val_loss: 40.3843
Epoch 5/100
29/29 - 0s - 9ms/step - loss: 23.1163 - val_loss: 39.3954
Epoch 6/100
29/29 - 0s - 8ms/step - loss: 17.9725 - val_loss: 36.0038
Epoch 7/100
29/29 - 0s - 7ms/step - loss: 16.9813 - val_loss: 40.5288
Epoch 8/100
29/29 - 0s - 4ms/step - loss: 19.5901 - val_loss: 33.3393
Epoch 9/100
29/29 - 0s - 3ms/step - loss: 17.8915 - val_loss: 29.2330
Epoch 10/100
29/29 - 0s - 3ms/step - loss: 16.5839 - val_loss: 31.4668
Epoch 11/100
29/29 - 0s - 3ms/step - loss: 16.3680 - val_loss: 36.2876
Epoch 12/100
29/29 - 0s - 3ms/step - loss: 16.7522 - val_loss: 29.1514
Epoch 13/100
29/29 - 0s - 5ms/step - loss: 15.2495 - val_loss: 28.3523
Epoch 14/100
29/29 - 0s - 3ms/step - loss: 15.3164 - val_loss: 35.0324
Epoch 15/100
29/29 - 0s - 3ms/step - loss: 15.1840 - val_loss: 28.5325
Epoch 16/100
29/29 - 0s - 3ms/step - loss: 15.2179 - val_loss: 27.1282
Epoch 17/100
29/29 - 0s - 4ms/step - loss: 14.1745 - val_loss: 26.0087
Epoch 18/100
29/29 - 0s - 4ms/step - loss: 13.7819 - val_loss: 24.8824
Epoch 19/100
29/29 - 0s - 3ms/step - loss: 13.8806 - val_loss: 26.3208
Epoch 20/100
29/29 - 0s - 3ms/step - loss: 14.0206 - val_loss: 23.1735
Epoch 21/100
29/29 - 0s - 3ms/step - loss: 13.9922 - val_loss: 25.3729
Epoch 22/100
29/29 - 0s - 3ms/step - loss: 14.4743 - val_loss: 30.4632
Epoch 23/100
29/29 - 0s - 3ms/step - loss: 14.4264 - val_loss: 25.6162
Epoch 24/100
29/29 - 0s - 3ms/step - loss: 15.9910 - val_loss: 32.0840
Epoch 25/100
29/29 - 0s - 3ms/step - loss: 14.4568 - val_loss: 21.5007
Epoch 26/100
29/29 - 0s - 4ms/step - loss: 13.3163 - val_loss: 27.3285
Epoch 27/100
29/29 - 0s - 6ms/step - loss: 13.0682 - val_loss: 22.2944
Epoch 28/100
29/29 - 0s - 5ms/step - loss: 12.8923 - val_loss: 21.6356
Epoch 29/100
29/29 - 0s - 11ms/step - loss: 14.8101 - val_loss: 22.4935
Epoch 30/100
29/29 - 0s - 4ms/step - loss: 12.5160 - val_loss: 26.1538
Epoch 31/100
29/29 - 0s - 6ms/step - loss: 13.5757 - val_loss: 22.6943
Epoch 32/100
29/29 - 0s - 7ms/step - loss: 13.9723 - val_loss: 24.2004
Epoch 33/100
29/29 - 0s - 7ms/step - loss: 12.2745 - val_loss: 25.3501
Epoch 34/100
29/29 - 0s - 4ms/step - loss: 12.3732 - val_loss: 20.2907
Epoch 35/100
29/29 - 0s - 4ms/step - loss: 16.4767 - val_loss: 21.3532
Epoch 36/100
29/29 - 0s - 3ms/step - loss: 17.5176 - val_loss: 21.7693
Epoch 37/100
29/29 - 0s - 4ms/step - loss: 15.3345 - val_loss: 21.4498
Epoch 38/100
29/29 - 0s - 4ms/step - loss: 13.8575 - val_loss: 24.2778
Epoch 39/100
29/29 - 0s - 3ms/step - loss: 13.5363 - val_loss: 20.8722
Epoch 40/100
29/29 - 0s - 4ms/step - loss: 13.1047 - val_loss: 25.0431
Epoch 41/100
29/29 - 0s - 4ms/step - loss: 11.7824 - val_loss: 23.3268
Epoch 42/100
29/29 - 0s - 4ms/step - loss: 12.4010 - val_loss: 19.9793
Epoch 43/100
29/29 - 0s - 3ms/step - loss: 12.1213 - val_loss: 24.8932
Epoch 44/100
29/29 - 0s - 5ms/step - loss: 12.6308 - val_loss: 19.7896
Epoch 45/100
29/29 - 0s - 4ms/step - loss: 12.4618 - val_loss: 19.7197
Epoch 46/100
29/29 - 0s - 3ms/step - loss: 11.2426 - val_loss: 19.3681
Epoch 47/100
29/29 - 0s - 3ms/step - loss: 13.7359 - val_loss: 18.2378
Epoch 48/100
29/29 - 0s - 3ms/step - loss: 12.0863 - val_loss: 20.2873
Epoch 49/100
29/29 - 0s - 3ms/step - loss: 10.9082 - val_loss: 19.6553
Epoch 50/100
29/29 - 0s - 3ms/step - loss: 11.5076 - val_loss: 21.4888
Epoch 51/100
29/29 - 0s - 3ms/step - loss: 12.6264 - val_loss: 20.1206
Epoch 52/100
29/29 - 0s - 4ms/step - loss: 14.9802 - val_loss: 21.7859
Epoch 53/100
29/29 - 0s - 3ms/step - loss: 12.1967 - val_loss: 17.0974
Epoch 54/100
29/29 - 0s - 4ms/step - loss: 10.8399 - val_loss: 25.3481
Epoch 55/100
29/29 - 0s - 4ms/step - loss: 11.5415 - val_loss: 17.0192
Epoch 56/100
29/29 - 0s - 3ms/step - loss: 12.7456 - val_loss: 21.7147
Epoch 57/100
29/29 - 0s - 4ms/step - loss: 12.0770 - val_loss: 18.9949
Epoch 58/100
29/29 - 0s - 3ms/step - loss: 11.6276 - val_loss: 19.6378
Epoch 59/100
29/29 - 0s - 4ms/step - loss: 11.3897 - val_loss: 19.7215
Epoch 60/100
29/29 - 0s - 4ms/step - loss: 10.5409 - val_loss: 17.8577
Epoch 61/100
29/29 - 0s - 5ms/step - loss: 10.8012 - val_loss: 19.2403
Epoch 62/100
29/29 - 0s - 3ms/step - loss: 11.6931 - val_loss: 17.6348
Epoch 63/100
29/29 - 0s - 3ms/step - loss: 11.5452 - val_loss: 18.8797
Epoch 64/100
29/29 - 0s - 3ms/step - loss: 11.3489 - val_loss: 20.4486
Epoch 65/100
29/29 - 0s - 3ms/step - loss: 11.1095 - val_loss: 17.7837
Epoch 66/100
29/29 - 0s - 4ms/step - loss: 11.3402 - val_loss: 18.3359
Epoch 67/100
29/29 - 0s - 4ms/step - loss: 10.8005 - val_loss: 18.1141
Epoch 68/100
29/29 - 0s - 3ms/step - loss: 11.8449 - val_loss: 18.3160
Epoch 69/100
29/29 - 0s - 3ms/step - loss: 10.2608 - val_loss: 17.6553
Epoch 70/100
29/29 - 0s - 3ms/step - loss: 10.2302 - val_loss: 19.8449
Epoch 71/100
29/29 - 0s - 4ms/step - loss: 10.1480 - val_loss: 17.0305
Epoch 72/100
29/29 - 0s - 3ms/step - loss: 10.1298 - val_loss: 17.4777
Epoch 73/100
29/29 - 0s - 3ms/step - loss: 10.7564 - val_loss: 26.5767
Epoch 74/100
29/29 - 0s - 3ms/step - loss: 11.1559 - val_loss: 19.9871
Epoch 75/100
29/29 - 0s - 4ms/step - loss: 10.7779 - val_loss: 17.4053
Epoch 76/100
29/29 - 0s - 4ms/step - loss: 10.7170 - val_loss: 17.3261
Epoch 77/100
29/29 - 0s - 4ms/step - loss: 10.5994 - val_loss: 18.8068
Epoch 78/100
29/29 - 0s - 4ms/step - loss: 10.1323 - val_loss: 24.1866
Epoch 79/100
29/29 - 0s - 4ms/step - loss: 11.0158 - val_loss: 17.5307
Epoch 80/100
29/29 - 0s - 4ms/step - loss: 11.4599 - val_loss: 17.3514
Epoch 81/100
29/29 - 0s - 4ms/step - loss: 10.6028 - val_loss: 19.5136
Epoch 82/100
29/29 - 0s - 4ms/step - loss: 11.3729 - val_loss: 18.6711
Epoch 83/100
29/29 - 0s - 4ms/step - loss: 9.8945 - val_loss: 16.5424
Epoch 84/100
29/29 - 0s - 4ms/step - loss: 10.4601 - val_loss: 16.5192
Epoch 85/100
29/29 - 0s - 4ms/step - loss: 10.0678 - val_loss: 19.3247
Epoch 86/100
29/29 - 0s - 4ms/step - loss: 10.0461 - val_loss: 16.8478
Epoch 87/100
29/29 - 0s - 4ms/step - loss: 9.3490 - val_loss: 17.9896
Epoch 88/100
29/29 - 0s - 4ms/step - loss: 9.8102 - val_loss: 29.3482
Epoch 89/100
29/29 - 0s - 4ms/step - loss: 11.2283 - val_loss: 17.3499
Epoch 90/100
29/29 - 0s - 4ms/step - loss: 9.7630 - val_loss: 18.0996
Epoch 91/100
29/29 - 0s - 4ms/step - loss: 11.9178 - val_loss: 15.2379
Epoch 92/100
29/29 - 0s - 4ms/step - loss: 11.8425 - val_loss: 16.9437
Epoch 93/100
29/29 - 0s - 3ms/step - loss: 9.4511 - val_loss: 17.6536
Epoch 94/100
29/29 - 0s - 4ms/step - loss: 9.2379 - val_loss: 16.2321
Epoch 95/100
29/29 - 0s - 4ms/step - loss: 8.9123 - val_loss: 15.6584
Epoch 96/100
29/29 - 0s - 4ms/step - loss: 9.2739 - val_loss: 17.0447
Epoch 97/100
29/29 - 0s - 4ms/step - loss: 9.7376 - val_loss: 22.3075
Epoch 98/100
29/29 - 0s - 4ms/step - loss: 10.3270 - val_loss: 20.7225
Epoch 99/100
29/29 - 0s - 4ms/step - loss: 10.1149 - val_loss: 17.0291
Epoch 100/100
29/29 - 0s - 4ms/step - loss: 9.1301 - val_loss: 33.3519

Based on the results, we notice that:

- Adding more hidden layers to the model increases its capacity to learn and represent complex relationships within the data. This allows the model to better identify, as a result, the model becomes more effective at fitting the training data and potentially improving its predictions.
- By reducing the proportion of data set aside for validation and using a larger portion for training, the model has access to more examples to learn from. This additional training data helps the model improve its understanding of the underlying trends, which can lead to better overall performance.